### ISSUE TITLE
Embed stackedit-container into a div

### ISSUE THREAD

**Issue by lmberry** [benweet/stackedit.js#10]
Using the get started, i was able to embed StackEdit into my page, but it takes the entire window.

I would like to contain stackedit into my own element, such as a div, to control the size.  I can't seem to figure out how though.

I am using Vuejs though importing stackedit-js in the classic way the Readme is describing.

**Comment by benweet** [comment]
The popup style is the main functionality of this library. I think it would be easier to fork the script for your own needs rather than trying to cover all the use cases.
