### ISSUE TITLE
Why send the whole text content to StackEdit?

### ISSUE THREAD

**Issue by Doidel** [benweet/stackedit.js#23]
Hello bentweet

First and foremost thanks for this awesome editor!

I just noticed while reading through your stackedit.js, that you send the whole text content as a param in the src of the iframe:
`const params = {

      contentText: content.text,

    };
...
iframeEl.src = urlParser.href;`

For these reasons I would prefer if the content was sent by message (and maybe also the title):
- Intellectual Property / Piracy: Some texts are not meant for the public, yet like that they are exposed
- StackEdit needlessly wastes a lot of internet traffic
- GET has a very small maximum amount of characters (usually 2'048)

Please tell me if you object to (some of) these issues. Otherwise I would greatly appreciate if at least the content was sent by message! 👍 

Best regards
Doidel

**Comment by benweet** [comment]
The content is sent as a hash parameter. It's not sent to any server.

**Comment by Doidel** [comment]
Oh alright, learnt something :) Thanks for the clarification!
